/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liteshiftwindow;

import java.awt.Font;
import java.awt.Frame;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JRootPane;

/**
 *
 * @author Matthew
 */
public class editAvailabilityForm extends javax.swing.JFrame {

    /**
     * Creates new form editAvailabilityForm
     */
    public editAvailabilityForm() {
        initComponents();
    }

    public Employee editedEmployee;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbSSunM = new javax.swing.JCheckBox();
        cbSSunA = new javax.swing.JCheckBox();
        cbSSunN = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        cbSMonM = new javax.swing.JCheckBox();
        cbSMonA = new javax.swing.JCheckBox();
        cbSMonN = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        cbSTueM = new javax.swing.JCheckBox();
        cbSTueA = new javax.swing.JCheckBox();
        cbSTueN = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        cbSWedM = new javax.swing.JCheckBox();
        cbSWedA = new javax.swing.JCheckBox();
        cbSWedN = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        cbSThuM = new javax.swing.JCheckBox();
        cbSThuA = new javax.swing.JCheckBox();
        cbSThuN = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        cbSFriN = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        cbSFriM = new javax.swing.JCheckBox();
        cbSFriA = new javax.swing.JCheckBox();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        cbSSatM = new javax.swing.JCheckBox();
        cbSSatA = new javax.swing.JCheckBox();
        cbSSatN = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbHSunM = new javax.swing.JCheckBox();
        cbHSunA = new javax.swing.JCheckBox();
        cbHSunN = new javax.swing.JCheckBox();
        jSeparator13 = new javax.swing.JSeparator();
        cbHMonM = new javax.swing.JCheckBox();
        cbHMonA = new javax.swing.JCheckBox();
        cbHMonN = new javax.swing.JCheckBox();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        cbHTueM = new javax.swing.JCheckBox();
        cbHTueA = new javax.swing.JCheckBox();
        cbHTueN = new javax.swing.JCheckBox();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        cbHWedM = new javax.swing.JCheckBox();
        cbHWedA = new javax.swing.JCheckBox();
        cbHWedN = new javax.swing.JCheckBox();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        cbHThuM = new javax.swing.JCheckBox();
        cbHThuA = new javax.swing.JCheckBox();
        cbHThuN = new javax.swing.JCheckBox();
        jSeparator17 = new javax.swing.JSeparator();
        cbHFriN = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        cbHFriM = new javax.swing.JCheckBox();
        cbHFriA = new javax.swing.JCheckBox();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        cbHSatM = new javax.swing.JCheckBox();
        cbHSatA = new javax.swing.JCheckBox();
        cbHSatN = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Daily Availability");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel11.setText("SUN");

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel12.setText("MON");

        cbSSunM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSunMActionPerformed(evt);
            }
        });

        cbSSunA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSunAActionPerformed(evt);
            }
        });

        cbSSunN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSunNActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel15.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel15.setText("TUE");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel16.setText("WED");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel17.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel17.setText("THU");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel18.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel18.setText("FRI");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel19.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel19.setText("SAT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSSunM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSSunA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSSunN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSMonM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSMonA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSMonN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSTueM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSTueA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSTueN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSWedM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSWedA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSWedN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSThuM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSThuA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSThuN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSFriM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSFriA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSFriN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSSatM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSSatA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSSatN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbSSunM)
                                                .addComponent(cbSSunA)
                                                .addComponent(cbSSunN)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbSMonM))))
                                .addComponent(jSeparator1)
                                .addComponent(cbSMonA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSMonN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSTueM))
                                .addComponent(cbSTueA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSTueN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSWedM))
                                .addComponent(cbSWedA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSWedN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSThuM))
                                .addComponent(cbSThuA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSThuN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSFriM))
                                .addComponent(cbSFriA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSFriN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSSatM))
                                .addComponent(cbSSatA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSSatN, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel25.setText("SUN");

        jLabel26.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel26.setText("MON");

        cbHSunM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHSunMActionPerformed(evt);
            }
        });

        cbHSunA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHSunAActionPerformed(evt);
            }
        });

        cbHSunN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHSunNActionPerformed(evt);
            }
        });

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel27.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel27.setText("TUE");

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel28.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel28.setText("WED");

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel29.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel29.setText("THU");

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel30.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel30.setText("FRI");

        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel31.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel31.setText("SAT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbHSunM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHSunA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHSunN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbHMonM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHMonA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHMonN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbHTueM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHTueA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHTueN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbHWedM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHWedA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHWedN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbHThuM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHThuA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHThuN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbHFriM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHFriA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHFriN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbHSatM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHSatA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHSatN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14)
                    .addComponent(jSeparator15)
                    .addComponent(jSeparator16)
                    .addComponent(jSeparator17)
                    .addComponent(jSeparator18)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel26))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbHSunM)
                                                .addComponent(cbHSunA)
                                                .addComponent(cbHSunN)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbHMonM))))
                                .addComponent(jSeparator13)
                                .addComponent(cbHMonA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbHMonN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHTueM))
                                .addComponent(cbHTueA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbHTueN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHWedM))
                                .addComponent(cbHWedA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbHWedN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHThuM))
                                .addComponent(cbHThuA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbHThuN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHFriM))
                                .addComponent(cbHFriA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbHFriN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHSatM))
                                .addComponent(cbHSatA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbHSatN, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setText("Soft Constraints");

        jLabel2.setText("Hard Constraints");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void populateCheckBoxes(boolean [][] soft, boolean [][] hard){
        javax.swing.JCheckBox softCBList [][] = {{this.cbSSunM,this.cbSSunA,this.cbSSunN},{this.cbSMonM,this.cbSMonA,this.cbSMonN},{this.cbSTueM,this.cbSTueA,this.cbSTueN},{this.cbSWedM,this.cbSWedA,this.cbSWedN},{this.cbSThuM,this.cbSThuA,this.cbSThuN},{this.cbSFriM,this.cbSFriA,this.cbSFriN},{this.cbSSatM,this.cbSSatA,this.cbSSatN}};
        javax.swing.JCheckBox hardCBList [][] = {{this.cbHSunM,this.cbHSunA,this.cbHSunN},{this.cbHMonM,this.cbHMonA,this.cbHMonN},{this.cbHTueM,this.cbHTueA,this.cbHTueN},{this.cbHWedM,this.cbHWedA,this.cbHWedN},{this.cbHThuM,this.cbHThuA,this.cbHThuN},{this.cbHFriM,this.cbHFriA,this.cbHFriN},{this.cbHSatM,this.cbHSatA,this.cbHSatN}};
        
        for(int i = 0; i <  7; i++){
            for (int j = 0; j < 3; j++){
                softCBList[i][j].setSelected(soft[i][j]);
                hardCBList[i][j].setSelected(hard[i][j]);
            }
        }
    }
    
    public void setupSaveAvailWizard(firstRunWizard frw){          
        javax.swing.JCheckBox softCBList [][] = {{this.cbSSunM,this.cbSSunA,this.cbSSunN},{this.cbSMonM,this.cbSMonA,this.cbSMonN},{this.cbSTueM,this.cbSTueA,this.cbSTueN},{this.cbSWedM,this.cbSWedA,this.cbSWedN},{this.cbSThuM,this.cbSThuA,this.cbSThuN},{this.cbSFriM,this.cbSFriA,this.cbSFriN},{this.cbSSatM,this.cbSSatA,this.cbSSatN}};
        javax.swing.JCheckBox hardCBList [][] = {{this.cbHSunM,this.cbHSunA,this.cbHSunN},{this.cbHMonM,this.cbHMonA,this.cbHMonN},{this.cbHTueM,this.cbHTueA,this.cbHTueN},{this.cbHWedM,this.cbHWedA,this.cbHWedN},{this.cbHThuM,this.cbHThuA,this.cbHThuN},{this.cbHFriM,this.cbHFriA,this.cbHFriN},{this.cbHSatM,this.cbHSatA,this.cbHSatN}};
        for(int i = 0; i < 7; i++){
            for(int j = 0; j < 3; j++){
                frw.softAvail[i][j] = softCBList[i][j].isSelected();
                frw.hardAvail[i][j] = hardCBList[i][j].isSelected(); 
            }
        }  
        
    }
    
    public void setupSaveAvailEmployee(AddEmployeeForm aef){
        javax.swing.JCheckBox softCBList [][] = {{this.cbSSunM,this.cbSSunA,this.cbSSunN},{this.cbSMonM,this.cbSMonA,this.cbSMonN},{this.cbSTueM,this.cbSTueA,this.cbSTueN},{this.cbSWedM,this.cbSWedA,this.cbSWedN},{this.cbSThuM,this.cbSThuA,this.cbSThuN},{this.cbSFriM,this.cbSFriA,this.cbSFriN},{this.cbSSatM,this.cbSSatA,this.cbSSatN}};
        javax.swing.JCheckBox hardCBList [][] = {{this.cbHSunM,this.cbHSunA,this.cbHSunN},{this.cbHMonM,this.cbHMonA,this.cbHMonN},{this.cbHTueM,this.cbHTueA,this.cbHTueN},{this.cbHWedM,this.cbHWedA,this.cbHWedN},{this.cbHThuM,this.cbHThuA,this.cbHThuN},{this.cbHFriM,this.cbHFriA,this.cbHFriN},{this.cbHSatM,this.cbHSatA,this.cbHSatN}};
        for(int i = 0; i < 7; i++){
            for(int j = 0; j < 3; j++){
                aef.softAvail[i][j] = softCBList[i][j].isSelected();
                aef.hardAvail[i][j] = hardCBList[i][j].isSelected(); 
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Frame [] frameArray = Frame.getFrames();
        for (Frame curFrame : frameArray){
            if (curFrame.getTitle().equals("Add Employee") && (((AddEmployeeForm) curFrame).editedEmployee.Name).equals(editedEmployee.Name) ) {
                AddEmployeeForm aef = (AddEmployeeForm) curFrame;
                
                javax.swing.JCheckBox softCBList [][] = {{this.cbSSunM,this.cbSSunA,this.cbSSunN},{this.cbSMonM,this.cbSMonA,this.cbSMonN},{this.cbSTueM,this.cbSTueA,this.cbSTueN},{this.cbSWedM,this.cbSWedA,this.cbSWedN},{this.cbSThuM,this.cbSThuA,this.cbSThuN},{this.cbSFriM,this.cbSFriA,this.cbSFriN},{this.cbSSatM,this.cbSSatA,this.cbSSatN}};
                javax.swing.JCheckBox hardCBList [][] = {{this.cbHSunM,this.cbHSunA,this.cbHSunN},{this.cbHMonM,this.cbHMonA,this.cbHMonN},{this.cbHTueM,this.cbHTueA,this.cbHTueN},{this.cbHWedM,this.cbHWedA,this.cbHWedN},{this.cbHThuM,this.cbHThuA,this.cbHThuN},{this.cbHFriM,this.cbHFriA,this.cbHFriN},{this.cbHSatM,this.cbHSatA,this.cbHSatN}};
                for(int i = 0; i < 7; i++){
                    for(int j = 0; j < 3; j++){
                        aef.softAvail[i][j] = softCBList[i][j].isSelected();
                        aef.hardAvail[i][j] = hardCBList[i][j].isSelected(); 
                    }
                }
                this.dispose();
                return;
            }
        }
        
        
        boolean firstRun = false;
        for (Frame curFrame : frameArray){
            if (curFrame.getTitle().equals("Setup Wizard")) {
                firstRunWizard frw = (firstRunWizard) curFrame;
                firstRun = true;
                setupSaveAvailWizard(frw);
                this.dispose();
                return;
            }
        }
        
        
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbSSunMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSunMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSSunMActionPerformed

    private void cbSSunAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSunAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSSunAActionPerformed

    private void cbSSunNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSunNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSSunNActionPerformed

    private void cbHSunMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHSunMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHSunMActionPerformed

    private void cbHSunAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHSunAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHSunAActionPerformed

    private void cbHSunNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHSunNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHSunNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editAvailabilityForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbHFriA;
    private javax.swing.JCheckBox cbHFriM;
    private javax.swing.JCheckBox cbHFriN;
    private javax.swing.JCheckBox cbHMonA;
    private javax.swing.JCheckBox cbHMonM;
    private javax.swing.JCheckBox cbHMonN;
    private javax.swing.JCheckBox cbHSatA;
    private javax.swing.JCheckBox cbHSatM;
    private javax.swing.JCheckBox cbHSatN;
    private javax.swing.JCheckBox cbHSunA;
    private javax.swing.JCheckBox cbHSunM;
    private javax.swing.JCheckBox cbHSunN;
    private javax.swing.JCheckBox cbHThuA;
    private javax.swing.JCheckBox cbHThuM;
    private javax.swing.JCheckBox cbHThuN;
    private javax.swing.JCheckBox cbHTueA;
    private javax.swing.JCheckBox cbHTueM;
    private javax.swing.JCheckBox cbHTueN;
    private javax.swing.JCheckBox cbHWedA;
    private javax.swing.JCheckBox cbHWedM;
    private javax.swing.JCheckBox cbHWedN;
    private javax.swing.JCheckBox cbSFriA;
    private javax.swing.JCheckBox cbSFriM;
    private javax.swing.JCheckBox cbSFriN;
    private javax.swing.JCheckBox cbSMonA;
    private javax.swing.JCheckBox cbSMonM;
    private javax.swing.JCheckBox cbSMonN;
    private javax.swing.JCheckBox cbSSatA;
    private javax.swing.JCheckBox cbSSatM;
    private javax.swing.JCheckBox cbSSatN;
    private javax.swing.JCheckBox cbSSunA;
    private javax.swing.JCheckBox cbSSunM;
    private javax.swing.JCheckBox cbSSunN;
    private javax.swing.JCheckBox cbSThuA;
    private javax.swing.JCheckBox cbSThuM;
    private javax.swing.JCheckBox cbSThuN;
    private javax.swing.JCheckBox cbSTueA;
    private javax.swing.JCheckBox cbSTueM;
    private javax.swing.JCheckBox cbSTueN;
    private javax.swing.JCheckBox cbSWedA;
    private javax.swing.JCheckBox cbSWedM;
    private javax.swing.JCheckBox cbSWedN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
